### ISSUE TITLE
Add icon to non-wiki links

### ISSUE THREAD

**Issue by srid** [srid/emanote#136]
### Discussed in https://github.com/srid/emanote/discussions/135

<div type='discussions-op-text'>

<sup>Originally posted by **j-steinbach** September 21, 2021</sup>
This might be a customizable HTML/CSS thing, but Emanote should add icons to local and external links. 

Benefits: 
- I see exactly which link leads to an internal note/node that holds a meaningful conversation and which I can edit and have control of.
- I see which link leads me to an external page which moves me out of my ZK.

See [this](https://note.ema.srid.ca/resources/vscode) emanote page for example. It should be signaled that the first link (Visual Studio Code) is external, whereas the second link (emanote-template) is internal.

This is also how it is done on Wikipedia (just check the sources footer), with an icon that is similar to [this](https://fontawesome.com/v5.15/icons?d=gallery&p=2&q=external).</div>

**Comment by kukimik** [comment]
To keep things consistent (see https://github.com/srid/emanote/pull/176#issuecomment-943670927) perhaps the icon should be taken from https://heroicons.com/ (type "external-link" in the search box) instead of fontawesome.

**Comment by kukimik** [comment]
This is not as easy as it seems. The color of the icon should fit the color of the link text, which depends on the theme.

Aa far as I know, the Wikipedia approach (using the icon as a background image) does not allow us to change the color of the icon using `currentColor`. The same applies to placing the icon as `content` in the `:after` pseudo-element. 

One solution is to use a font (e.g. the fontawesome web font) instead of an svg icon and place the letter as content in the `:after` pseudo-element. I think this should work, but it needs to use the web font. I'm not sure if you are ok with that. Moreover, I don't know if a webfont for heroicons is available.

We also _could_ modify the inline svg on-the-fly in the `.tpl` file, but I think this would require manually handling the colors used by tailwind and will stop working if one decides to restyle the links.

Another option is to include the image in the DOM inside the `<a>` tag (I believe this can be done in `pandoc.tpl`), but this changes the semantics of the document.

We also can use a mask trick (I've learned it [here](https://selleo.com/til/posts/sflr8f0tok-svg-icons-in-pseudo-elements) and  [here](https://stackoverflow.com/a/42317014/5603549) ):

```css
a.emanote-external:after
{
  content: '';
  -webkit-mask: url("data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' class='h-5 w-5 xxx' viewBox='0 0 20 20'%3E%3Cpath d='M11 3a1 1 0 100 2h2.586l-6.293 6.293a1 1 0 101.414 1.414L15 6.414V9a1 1 0 102 0V4a1 1 0 00-1-1h-5z' /%3E%3Cpath d='M5 5a2 2 0 00-2 2v8a2 2 0 002 2h8a2 2 0 002-2v-3a1 1 0 10-2 0v3H5V7h3a1 1 0 000-2H5z' /%3E%3C/svg%3E") no-repeat 50% 50%;
  mask: url("data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' class='h-5 w-5 xxx' viewBox='0 0 20 20'%3E%3Cpath d='M11 3a1 1 0 100 2h2.586l-6.293 6.293a1 1 0 101.414 1.414L15 6.414V9a1 1 0 102 0V4a1 1 0 00-1-1h-5z' /%3E%3Cpath d='M5 5a2 2 0 00-2 2v8a2 2 0 002 2h8a2 2 0 002-2v-3a1 1 0 10-2 0v3H5V7h3a1 1 0 000-2H5z' /%3E%3C/svg%3E") no-repeat 50% 50%;
  -webkit-mask-size: cover;
  mask-size: cover;
  display: inline-block;
  height: 14px;
  width: 14px;
  background-color: currentColor;
}
```

This is somewhat hacky and does not work in all browsers (but [should be ok for 97% of users](https://caniuse.com/css-masks)). I've only checked it in a recent version of Firefox and Chromium. It is, however, easy to implement.
