### ISSUE TITLE
Multiple default HTML templates (aka. themes)

### ISSUE THREAD

**Issue by srid** [srid/emanote#21]
Currently we have exactly one default HTML template at [`./templates`](https://github.com/srid/emanote/tree/master/docs/templates).

Let's move that one level down, such as to make it possible to have multiple template themes as emanote provided defaults:

- `./templates/main/`
- `./templates/neuron/`

We can "select" a template from the .yaml data. For `index.yaml` contains this:

```yaml
template:
  # Use file "${template.name}.tpl" to render HTML
  name: templates/_default
```

(https://github.com/srid/emanote/pull/26 addes the "templates/" prefix)

When implementing this I suppose we could change that to `name: templates/main/_default` (and may as well rename "_default.tpl" to "index.tpl" to avoid confusion). Alternative ideas?
