### ISSUE TITLE
Stork search unicode issue in title

### ISSUE THREAD

**Issue by srid** [srid/emanote#336]
From @jilleJr https://github.com/EmaApps/emanote/pull/327#issuecomment-1214423019

> Emojis are broken in the search results. The `\U000...` part.
>
> ![image](https://user-images.githubusercontent.com/3998/185264281-a722dbe3-d8f7-4e31-93a7-1ce004a76ccd.png)

@srid I found the cause. I made Emanote write the TOML file it pipes to stork to a file, and in it we find:

```toml
[[input.files]]
  path = "./docs/demo/markdown.md"
  title = "Extended Markdown \\U0000270d\\U0000fe0f"
  url = "demo/markdown.html"
```

It's escaping the unicode-syntax. It should only be 1 backslash there.

![image](https://user-images.githubusercontent.com/2477952/184549098-c43164dc-4792-411c-a05d-8ca44250f657.png)

I.e, it seems to be somewhere in the haskell code that's causing this

_Originally posted by @jilleJr in https://github.com/EmaApps/emanote/issues/327#issuecomment-1214423019_
